import { Link } from 'react-router-dom'
import PageHero from '../components/PageHero'
import './LegalPages.css'

function PrivacyPolicyPage() {
  return (
    <>
      <PageHero
        eyebrow="Legal Information"
        title="Privacy Policy"
        text="How Shuaib Sulaiman & Co collects, uses, stores and protects personal information submitted through this website."
      />

      <section className="legal-page section">
        <div className="legal-summary">
          <p className="section-label">Last updated</p>
          <h2>28 July 2026</h2>
          <p>
            This Privacy Policy applies to the Shuaib Sulaiman & Co website and to enquiries submitted through our online forms.
          </p>
        </div>

        <div className="legal-content">
          <section>
            <h2>1. Who we are</h2>
            <p>
              Shuaib Sulaiman & Co is a Nigerian trading, export and consulting business. Our contact address is
              {' '}<strong>63 Pent City Estate, Lokogoma, Abuja, Nigeria</strong>. You can contact us about privacy matters at
              {' '}<a href="mailto:shuaibsgeneralcontractors@gmail.com">shuaibsgeneralcontractors@gmail.com</a>.
            </p>
          </section>

          <section>
            <h2>2. Information we collect</h2>
            <p>When you submit an enquiry or request a quotation, we may collect:</p>
            <ul>
              <li>Your name, company name, email address and telephone number.</li>
              <li>The product you are interested in, destination country and order requirements.</li>
              <li>The contents of your message and any later correspondence with us.</li>
              <li>Technical information such as browser, device, IP address, security logs and website usage information that may be generated by our hosting, security or analytics providers.</li>
              <li>Administrator account and activity information for authorised staff using the website dashboard.</li>
            </ul>
          </section>

          <section>
            <h2>3. How we use your information</h2>
            <p>We use personal information to:</p>
            <ul>
              <li>Review and respond to product enquiries and quotation requests.</li>
              <li>Confirm product specifications, availability, packaging, delivery and commercial requirements.</li>
              <li>Communicate with prospective and existing customers.</li>
              <li>Maintain enquiry records, manage customer relationships and improve our services.</li>
              <li>Protect the website, investigate misuse and comply with legal or regulatory obligations.</li>
            </ul>
          </section>

          <section>
            <h2>4. Lawful bases</h2>
            <p>
              Depending on the circumstances, we process personal information because it is necessary to respond to your request,
              take steps before entering a contract, perform a contract, comply with a legal obligation, protect legitimate business
              interests, or because you have provided valid consent where consent is required.
            </p>
          </section>

          <section>
            <h2>5. Sharing and service providers</h2>
            <p>
              We do not sell personal information. We may share information only where reasonably necessary with authorised employees,
              suppliers, logistics providers, professional advisers, technology and hosting providers, email providers, payment or banking
              partners, regulators, customs authorities or law-enforcement bodies.
            </p>
            <p>
              Our website currently uses third-party infrastructure, including Cloudflare for hosting or security services and Supabase for
              enquiry storage, authentication and related website functions. These providers may process information on our behalf under their
              own security and privacy obligations.
            </p>
          </section>

          <section>
            <h2>6. International data transfers</h2>
            <p>
              Some service providers or business partners may process information outside Nigeria. Where this occurs, we take reasonable steps
              to use appropriate contractual, legal and security safeguards consistent with applicable data-protection requirements.
            </p>
          </section>

          <section>
            <h2>7. Retention</h2>
            <p>
              We retain information only for as long as reasonably necessary for enquiries, quotations, transactions, record-keeping, dispute
              resolution, security and legal obligations. Retention periods may differ depending on whether an enquiry develops into a commercial
              transaction.
            </p>
          </section>

          <section>
            <h2>8. Security</h2>
            <p>
              We use reasonable administrative, technical and organisational measures designed to protect personal information. However, no
              internet transmission or storage system can be guaranteed to be completely secure.
            </p>
          </section>

          <section>
            <h2>9. Your rights</h2>
            <p>
              Subject to applicable law, you may have rights to request access to your personal information, correction, deletion, restriction,
              objection, portability, withdrawal of consent and information about how your data is used. You may also complain to the Nigeria Data
              Protection Commission where you believe your data-protection rights have been infringed.
            </p>
            <p>
              To make a request, email <a href="mailto:shuaibsgeneralcontractors@gmail.com">shuaibsgeneralcontractors@gmail.com</a>. We may need to verify your identity
              before completing a request.
            </p>
          </section>

          <section>
            <h2>10. Cookies and similar technologies</h2>
            <p>
              The website may use essential cookies or similar technologies required for security, session management, website operation and
              administrator authentication. If optional analytics or advertising technologies are introduced, this policy and any cookie controls
              will be updated as required.
            </p>
          </section>

          <section>
            <h2>11. Children</h2>
            <p>
              This website is intended for business and commercial enquiries and is not directed at children. We do not knowingly collect personal
              information from children through the quotation form.
            </p>
          </section>

          <section>
            <h2>12. Changes to this policy</h2>
            <p>
              We may update this Privacy Policy to reflect changes to our services, technology or legal obligations. The updated date shown at the
              top of the page will identify the latest version.
            </p>
          </section>

          <div className="legal-contact-card">
            <h2>Privacy questions</h2>
            <p>Email us at <a href="mailto:shuaibsgeneralcontractors@gmail.com">shuaibsgeneralcontractors@gmail.com</a> or write to 63 Pent City Estate, Lokogoma, Abuja, Nigeria.</p>
            <Link className="primary-button" to="/contact">Contact Us</Link>
          </div>
        </div>
      </section>
    </>
  )
}

export default PrivacyPolicyPage
