export const products = [
  {
    slug: 's-s-shea-butter',
    name: 'S&S Shea Butter',
    category: 'Wellness',
    image: '/images/products/shea-butter.jpg',
    summary: 'Natural Nigerian shea butter supplied for cosmetic, personal-care, wellness and approved industrial applications.',
    overview: 'S&S Shea Butter is sourced from selected Nigerian producer communities and prepared for buyers who value consistency, responsible sourcing and dependable delivery. Raw or refined options may be discussed, with colour, odour, texture, grade and packaging confirmed before order approval.',
    benefits: [
      'Naturally rich emollient for skin and hair products',
      'Raw and refined options may be available',
      'Suitable for cosmetic and wellness manufacturing',
      'Bulk formats designed for commercial handling',
    ],
    applications: [
      'Body creams and lotions',
      'Haircare and scalp products',
      'Soap, balm and cosmetic production',
      'Approved food or industrial formulations',
    ],
    specifications: {
      'Product type': 'Raw or refined shea butter',
      Origin: 'Nigeria',
      'Quality focus': 'Colour, odour, texture, cleanliness and buyer specification',
      'Order basis': 'Specification-led bulk quotation',
    },
    packaging: [
      'Lined cartons',
      'Food-grade buckets or drums',
      'Sealed bulk blocks',
      'Buyer-approved export packaging',
    ],
    qualityPoints: [
      'Producer and batch selection',
      'Clean processing and storage',
      'Physical quality inspection',
      'Documentation and shipment control',
    ],
  },
  {
    slug: 's-s-garri-cassava',
    name: 'S&S Garri (Cassava)',
    category: 'Processed Food',
    image: '/images/products/garri-cassava-flakes.jpeg',
    summary: 'Clean, properly processed cassava flakes supplied for diaspora, retail, wholesale and food-service markets.',
    overview: 'S&S Garri is produced from selected cassava and coordinated for buyers requiring dependable processing, moisture control, granulation and export preparation. White or yellow garri may be supplied subject to availability and the agreed order specification.',
    benefits: [
      'Popular West African staple with strong diaspora demand',
      'Flexible pack sizes for retail or food service',
      'White and yellow options subject to availability',
      'Prepared for wholesale and container distribution',
    ],
    applications: [
      'African and international food stores',
      'Diaspora grocery markets',
      'Restaurants and catering businesses',
      'Wholesale and institutional food supply',
    ],
    specifications: {
      'Product type': 'Processed cassava flakes',
      Varieties: 'White or yellow garri',
      'Quality focus': 'Moisture, cleanliness, acidity and granulation',
      'Order basis': 'Container or agreed wholesale quantity',
    },
    packaging: [
      'Sealed consumer pouches',
      'Bulk woven or laminated bags',
      'Export cartons where required',
      'Custom labels subject to approval',
    ],
    qualityPoints: [
      'Supplier and batch verification',
      'Visual and moisture inspection',
      'Food-safe packing environment',
      'Export documentation coordination',
    ],
  },
  {
    slug: 's-s-cashew-nut',
    name: 'S&S Cashew Nut',
    category: 'Agricultural',
    image: '/images/products/raw-cashew-nuts.jpg',
    summary: 'Selected Nigerian cashew nuts supplied to processors, food manufacturers, packers and commodity buyers.',
    overview: 'S&S Cashew Nut is sourced according to season and buyer requirements. Raw nuts in shell or processed kernel options may be discussed, with nut count, outturn, kernel grade, moisture, colour, defects and packaging agreed before quotation.',
    benefits: [
      'Suitable for processing, roasting or direct packing',
      'Specifications can be matched to buyer requirements',
      'Seasonal procurement planning is available',
      'Bulk container supply for qualified buyers',
    ],
    applications: [
      'Cashew processing plants',
      'Snack and nut brands',
      'Bakery and confectionery production',
      'Commodity and ingredient distribution',
    ],
    specifications: {
      'Product type': 'Raw cashew nuts or processed kernels by agreement',
      'Quality indicators': 'Nut count, outturn, grade, moisture, colour and defects',
      Origin: 'Nigeria',
      'Order basis': 'Seasonal and grade-specific quotation',
    },
    packaging: [
      'Breathable jute or woven bags for raw nuts',
      'Vacuum-packed inner bags for kernels',
      'Food-grade cartons or tins',
      'Container loading with moisture protection',
    ],
    qualityPoints: [
      'Seasonal lot and supplier selection',
      'Sampling and grade assessment',
      'Moisture and defect checks',
      'Bagging, carton and container inspection',
    ],
  },
  {
    slug: 's-s-ginger',
    name: 'S&S Ginger',
    category: 'Agricultural',
    image: '/images/products/ginger.webp',
    summary: 'Nigerian ginger supplied in fresh, dried split or powdered formats for food, beverage and wellness markets.',
    overview: 'S&S Ginger is sourced from established Nigerian growing areas and prepared according to the buyer’s required form. Fresh roots, dried split ginger or ginger powder may be supplied subject to availability, with aroma, dryness, fibre, cleanliness and packaging confirmed before shipment.',
    benefits: [
      'Distinctive aroma and flavour profile',
      'Fresh, dried and processed formats may be available',
      'Suitable for food, beverage and wellness markets',
      'Export preparation tailored to destination requirements',
    ],
    applications: [
      'Spice and seasoning production',
      'Tea and beverage manufacturing',
      'Bakery and confectionery',
      'Extract and wellness-product processing',
    ],
    specifications: {
      'Product type': 'Fresh, dried split or powdered ginger',
      Origin: 'Nigeria',
      'Quality focus': 'Aroma, dryness, fibre, cleanliness and buyer specification',
      'Order basis': 'Format-specific quotation',
    },
    packaging: [
      'Ventilated cartons for fresh ginger',
      'Lined bags for dried ginger',
      'Sealed pouches or bags for powder',
      'Palletised export loading',
    ],
    qualityPoints: [
      'Root and batch selection',
      'Dryness and foreign-matter checks',
      'Ventilation or moisture-barrier controls',
      'Export documentation coordination',
    ],
  },
  {
    slug: 's-s-charcoal',
    name: 'S&S Charcoal',
    category: 'Energy & Minerals',
    image: '/images/products/s-s-charcoal.svg',
    summary: 'Selected charcoal supplied for approved commercial, industrial and hospitality uses, subject to destination regulations.',
    overview: 'S&S Charcoal is coordinated against clear buyer requirements covering wood source, lump size, fixed carbon, moisture, ash, burn characteristics and packaging. Supply is subject to responsible sourcing, export rules and destination-country requirements.',
    benefits: [
      'Lump-size and quality requirements can be agreed',
      'Suitable for commercial and hospitality buyers',
      'Bulk packaging supports container distribution',
      'Documentation coordinated for approved destinations',
    ],
    applications: [
      'Restaurants and hospitality operations',
      'Barbecue and grilling distribution',
      'Approved industrial heating applications',
      'Wholesale fuel distribution',
    ],
    specifications: {
      'Product type': 'Lump charcoal or buyer-agreed grade',
      'Quality focus': 'Fixed carbon, moisture, ash, size and burn performance',
      Origin: 'Nigeria',
      'Order basis': 'Technical and regulatory specification required',
    },
    packaging: [
      'Laminated export bags',
      'Buyer-branded retail bags',
      'Bulk sacks',
      'Moisture-protected container loading',
    ],
    qualityPoints: [
      'Responsible-source review',
      'Size and foreign-matter inspection',
      'Moisture and ash checks where agreed',
      'Export and destination compliance review',
    ],
  },
  {
    slug: 's-s-coal-black',
    name: 'S&S Coal (Black)',
    category: 'Energy & Minerals',
    image: '/images/products/s-s-coal-black.svg',
    summary: 'Black coal supplied to qualified industrial buyers against an agreed technical specification and regulatory review.',
    overview: 'S&S Coal (Black) is offered only for qualified commercial or industrial enquiries. Coal type, calorific value, sulphur, ash, moisture, particle size, volume, loading method, intended use and destination regulations must be confirmed before quotation or supply commitment.',
    benefits: [
      'Technical specification agreed before sourcing',
      'Bulk supply planning for qualified industrial buyers',
      'Sampling and analysis can be discussed',
      'Shipment documentation coordinated by destination',
    ],
    applications: [
      'Approved industrial energy use',
      'Manufacturing and process heating',
      'Qualified commodity distribution',
      'Other lawful buyer-specified applications',
    ],
    specifications: {
      'Product type': 'Black coal by agreed grade',
      'Technical indicators': 'Calorific value, sulphur, ash, moisture and particle size',
      'Supply condition': 'Subject to lawful sourcing and destination approval',
      'Order basis': 'Technical specification and compliance review required',
    },
    packaging: [
      'Bulk vessel or container loading where feasible',
      'Jumbo bags',
      'Bulk sacks',
      'Buyer-agreed industrial handling format',
    ],
    qualityPoints: [
      'Supplier and source verification',
      'Product sampling where agreed',
      'Weight and loading checks',
      'Environmental, export and customs document review',
    ],
  },
  {
    slug: 's-s-yam-flour-amala',
    name: 'S&S Yam Flour (Amala)',
    category: 'Processed Food',
    image: '/images/products/s-s-yam-flour.svg',
    summary: 'Finely processed yam flour prepared for amala, retail distribution, food service and diaspora markets.',
    overview: 'S&S Yam Flour (Amala) is produced from selected yam and prepared as a shelf-stable flour for buyers requiring consistent texture, colour, cleanliness and packaging. Pack size, labelling, moisture limits and destination requirements are confirmed before production and shipment.',
    benefits: [
      'Convenient shelf-stable Nigerian staple',
      'Suitable for amala preparation',
      'Retail and bulk pack sizes may be arranged',
      'Strong fit for diaspora and speciality-food markets',
    ],
    applications: [
      'African and international food stores',
      'Restaurants and catering businesses',
      'Wholesale food distribution',
      'Private-label retail programmes',
    ],
    specifications: {
      'Product type': 'Processed yam flour',
      Format: 'Fine flour for amala preparation',
      'Quality focus': 'Ingredient purity, dryness, texture, colour and shelf life',
      'Order basis': 'Pack and volume-specific quotation',
    },
    packaging: [
      'Printed retail pouches',
      'Bulk food-grade sacks',
      'Export master cartons',
      'Private-label packaging by agreement',
    ],
    qualityPoints: [
      'Raw material and processor review',
      'Moisture and cleanliness checks',
      'Seal and label inspection',
      'Batch documentation control',
    ],
  },
]

export const categories = ['All Products', 'Agricultural', 'Processed Food', 'Wellness', 'Energy & Minerals']

export const services = [
  {
    number: '01',
    title: 'Global Product Sourcing',
    text: 'We identify dependable producers and suppliers, coordinate samples and align product specifications with international buyer requirements.',
  },
  {
    number: '02',
    title: 'Export Logistics & Documentation',
    text: 'We support packaging, freight planning, customs documentation, inspection coordination and shipment preparation from Nigeria.',
  },
  {
    number: '03',
    title: 'Focused Product Exports',
    text: 'We supply our seven core S&S products to qualified wholesale, retail, hospitality and industrial buyers.',
  },
]

export const testimonials = [
  {
    quote: 'The team handled sourcing, packaging and export coordination professionally. Communication remained clear throughout the order.',
    name: 'Anny K.',
    role: 'Spice Importer, Dubai',
  },
  {
    quote: 'We received dependable support from enquiry through shipment. The quality-control process gave us confidence in the final delivery.',
    name: 'Ravi M.',
    role: 'Food Distributor, India',
  },
  {
    quote: 'A transparent and responsive trading partner. We were kept informed and received the agreed documentation on time.',
    name: 'Li W.',
    role: 'Wholesale Buyer, China',
  },
]
